- themes/contribute.jquery.org/cla-check.php
This depends on the jquery-license changes that expose the error details.
Fixes jquery/jquery-license#17
Ref jquery/jquery-license#38
Actual error output:
Compare to: http://contribute.jquery.org/CLA/status/?repo=globalize&sha=21b404d2c534dfb6b69c3cf1fdb0427082d147d2
> contribute.jquery.org: Show CLA error details, if available

- install.php
- mu-plugins/jquery-filters.php
- sunrise.php
Addresses #303:
* Update how a network is defined by assuming only one network exists and is defined in the configuration.
* Watch for the likely not to happen scenario where a second network is installed.
* Catch a case where the `site_admins` network option may not be properly set during installation locally.
* Allow `downloads.wordpress.org` URLs to survive the protocol relative filter so that local updates will work nicely. 
This takes a slightly different approach from @Ipstenu in #378 as there are quite a few gotchas hanging out there when running this outside of the Vagrant environment and/or when installing and upgrading.
There's probably room for future improvement, especially once the Vagrant box has been updated to use a newer version of WordPress by default. We could then …
> Update sunrise and allow newer versions of WordPress to work

- themes/irc.jquery.org/sidebar.php
I'm still unclear on why there is a [robots.txt that excludes the logs](https://github.com/dmethvin/jquery-wp-content/blob/aeefd86d4e834ba01b813646a0563b8e4ce7a928/themes/irc.jquery.org/robots.txt) but since PEP isn't excluding logs I figured I would give it a try without.
> Add grunt channels to sidebar

- themes/contribute.jquery.org/cla-check.php
cf. http://contribute.jquery.org/CLA/status/?owner=jquery&repo=jquery&sha=e217c1949f625c4c4ae7b9e93943310c73ef55ac
> contribute.jquery.org: Sanitize input before rendering as HTML

- themes/jquery/header.php
Try jQuery is no longer being offered. This commit works alongside
https://github.com/jquery/jquery.com/commit/9ac15a47a696d2c21a59cf025d4f5b4408bec80c
Closes https://github.com/jquery/jquery.com/issues/176.
~I would like to sign the CLA per the contributing guidelines, but I can't figure out how to sign the CLA at http://contribute.jquery.org/cla (which redirects to https://js.foundation/CLA for me).~
> Header: Remove "Try jQuery"

- themes/jquery/header.php
Any subpage or directory is currently yielding a 404 Not Found error for
the donate image.
Example: http://api.jquery.com/jQuery/
/cc @kborchers
> api.jquery.com: Fix 404 Not Found for donate img

- themes/jquery/footer-mobile.php
- themes/jquery/footer-qunit.php
- themes/jquery/footer-ui.php
- themes/jquery/footer.php
This PR will add DocSearch to all other documentation websites as https://jquery.com/. It will allow an user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.
If there is no result, pressing enter will enable the legacy search.
Follow #416
> All: Add Algolia's DocSearch to UI/Mobile/QUnit website searches

- themes/jquery/footer-bottom.php
Will close #427. This PR adds the boilerplate language and updated legal / policy links to the existing layout. I think we want to probably restyle this a bit but I am not a designer and would defer to others for how to address the layout:
> jquery: Add boilerplate language & links to the footer

- themes/jquery/css/base.css
- themes/jquery/header.php
Since for some time some sites will use an older version of
`grunt-jquery-content` that includes an older highlight.js version, for now both
types of CSS rules need to be present. The legacy ones have been marked with
comments.
The new version of highlight.js uses more generic class names, shared between
languages. That means there's no 1-1 correspondence between the old & the new
ones in all cases & some differences in syntax highlighting will be there.
That's 9 years of highlight.js updates, though!
Ref https://github.com/jquery/grunt-jquery-content/pull/81
> jquery: Fix CSS to account for the newest highlight.js

- themes/jquery/css/base.css
This PR uses the [well-supported](https://caniuse.com/mdn-css_properties_user-select)<sup>1</sup> `user-select: none` CSS property on the line number gutter in syntaxhighlighter code blocks, to prevent accidental inclusion when copy-pasting the contained code.
1. while `user-select: none` has broad browser support, both Safari versions do require its use as the vendor-prefixed `-webkit-user-select` (also included in the PR changes).
<s>(CLA Note: As I mentioned in jquery/contribute.jquery.org#149, the CLA links across the documentation are currently linking to an OpenJSF page with no CLA in evidence. I have not signed the CLA simply because I can't find any way _**to**_ sign it.)</s> Never mind, the bot's link worked.
> jquery: Make code-listing line numbers unselectable

- mu-plugins/jquery-filters.php
This adds a filter to prevent local redirects to live sites, specifically local.jquery.com to jquery.com and local.jqueryui.com to jqueryui.com. The culprit turned out to be a combination of wordpress redirecting indexes classified as "page" and the jquery-static-index.php plugin used on those sites. Thanks to @Krinkle for his help figuring this out.
> All: add option filter to prevent local homepage redirects

- themes/jquery/header.php
Upgrade jQuery to 3.7.0 for all jquery-wp-content sites. All sites have been tested locally.
It's possible I may have missed something, so I'll double check each site after deployment.
Fixes gh-400
> All: upgrade main jQuery to 3.7.0

- themes/jquery/css/sri-modal.css
- themes/releases.jquery.com/page.php
- also fixes a couple minor style issues with the tooltip
Before
After
> releases.jquery.com: upgrade jQuery UI to fix tooltip

- themes/jquery/css/sri-modal.css
- themes/jquery/js/sri-modal.js
- the SRI modal now resizes with the window
The modal on desktop is unchanged:
But mobile now goes from this:
To this:
> releases.jquery.com: make the SRI modal responsive

- themes/jquery/header.php
Added here:
Links to https://jquery.com/team
> jquery: add jQuery Team link to main header

- themes/jquery/css/base.css
* icon-muted
* icon-border
* icon-2x
* icon-3x
* icon-4x
* icon-spin
These appear to be unused, according to an org-wide search on GitHub, excluding matches in repos that don't use jquery-wp-content for their content (e.g. irc.jquery.org, bugs.jquery.com, and archived content repos such as web-events).
Ref https://github.com/jquery/jquery-wp-content/issues/455.
> All: remove unused FontAwesome utilities classes

- themes/jquery/js/main.js
This used to be done by Modernizr until its removal in 08f27c14ffc14c158b25e190cfa00125fb79c0d3. Some sites apply different styling for JS-disabled environments; one such example is the jQuery UI Download Builder which expands all Themeroller knobs sections in the no-JS mode.
> jquery: Add the `js` class, remove the `no-js` one

- plugins/jquery-filters.php
- localhost can still bypass this behavior by setting JQUERY_STAGING to 'local'
> plugins: restore puppet management of staging plugins

- sites.php
- themes/api.jqueryui.com/functions.php
- themes/api.jqueryui.com/index.php
- themes/releases.jquery.com/page.php
Also, update jQuery UI used on releases.jquery.com from 1.13.2 to 1.13.3.
> api.jqueryui.com: Prepare for jQuery UI 1.14

- themes/api.jquery.com/functions.php
- themes/api.jquerymobile.com/functions.php
- themes/api.jqueryui.com/functions.php
- themes/jquery/functions.php
- themes/jquery/header.php
Ref jquery/infrastructure-puppet#54
Ref jquery/infrastructure-puppet#57
This adds a filter that the API sites can override to allow for inline scripts and styles only in API demos.
I'm thinking we can use this in combination with a header set in infrastructure-puppet for non-wordpress sites.
> All: add Content-Security-Policy-Report-Only header to all wordpress sites

- themes/jquery/header.php
1. Some of these links started redirecting to different locations; update accordingly.
2. The website titled "Donate" and having "project-funding-opportunities" in the URL now redirects to the list of projects; change the name as well.
This should fix the failing spider check on api.jquery.com PRs.
> jquery: Fix links to pages on the OpenJS Foundation site

- plugins/jquery-filters.php
While debugging local setups with Andre, I noticed that when I changed port, the template assets continued to be served from port 80. This filter ensures that `theme_root_uri` includes the local port number, even after a database is populated with a portless siteurl, without the need to alter the database.
For whatever reason, Andre didn't have this issue when switching ports, but I did, and I couldn't tell you why this isn't always necessary.
> Local: ensure template assets use the correct port locally

- themes/api.jquery.com/style.css
- themes/jquery.com/style.css
- themes/jquery/css/base.css
- themes/jquery/functions.jquery.php
- themes/jquery/header.php
- themes/jquery/menu-header.php
I made some modifications to #467, including:
- generalized banner for future use
- set banner message explicitly in post meta (jquery.com's index lives in its repo, so we'll set that there). I set api.jquery.com's banner in its theme's index page. Before, the banner was showing on the homepage of all jQuery wordpress sites (e.g. jquerymobile.com), but we only want it to show on site specific to jQuery core (i.e. jquery.com and api.jquery.com).
- adjusted styles for version support warnings. used the fontawesome icon we are already loading instead of new svg.
Ref gh-467
Closes gh-462
See companion PRs for [jquery.com](https://github.com/jquery/jquery.com/pull/246) and [api.jquery.com](https://github.com/jquery/api.jquery.com/pull/1251).
> HeroDevs support

- themes/jquery/functions.jquery.php
- themes/jquery/header.php
* Switch from central list to per-url hash. This removes the need to know about and remember updating a central list. I noticed one file missing already, namely the typesense-minibar.js file.
This slightly improves cache use by not invalidating them all together.
* The filemtime timestamp values are so short that an MD5 hash of three filemtime() values is actually longer than just the three numbers concatenated. This means we lack the benefit a hash usually provides, which is that you get exposure to high entropy input in a format shorter than that same input.
* Switch from mtime (or mtime-hash) to content-hash. This has a few benefits:
- Note that Git does not track modified times. Instead, mtime is whenever a `git clone`, `checkout` or `pull` last created or modified the file locally on …
> All: add jq_url_append_version()

- themes/api.jquery.com/functions.php
- themes/jquery/css/sri-modal.css
- themes/jqueryui.com/functions.php
Mostly inline styles, with some styles and images loaded from download.jqueryui.com. See console at https://jqueryui.com/themeroller
- fixed an issue with the icon set for hover/active on the close button in the sri-modal at https://releases.jquery.com.
- added an exception for https://api.jquery.com/jQuery.getJSON, which uses the flickr api.
Ref https://github.com/jquery/infrastructure-puppet/issues/54
> jqueryui.com: add CSP exceptions for jQuery UI themeroller

- themes/jquery/functions.php
Ref https://github.com/jquery/infrastructure-puppet/issues/54
I've addressed all the legitimate reports I could find in the csp logs. I think we can switch to the enforced header and continue watching the logs for anything I may have missed.
The only remaining report headers will be on the blog sites (once we fix the issue with them not showing up).
> All: switch to enforced CSP header

- themes/jquery/functions.php
- when the blogs are switched to use this repo's jquery theme, the theme will need to allow for data: images and fonts. It still doesn't need to add exceptions for typekit as the fonts will be self-hosted.
- Also removed some redundant declarations. Anything not specified falls back to `default-src`, so setting `self` again isn't necessary.
Ref https://github.com/jquery/blog.jquery.com-theme/pull/12
> All: add CSP exceptions for wordpress admins

- themes/jquery/header.php
- themes/jquerymobile.com/functions.php
Fixes https://github.com/jquery/jquerymobile.com/issues/179
> jquerymobile.com: add CSP exceptions for mobile download builder

- themes/jquerymobile.com/functions.php
Ref https://github.com/jquery/jquerymobile.com/issues/179
> jquerymobile.com: add frame-src CSP exceptions for mobile download builder

- themes/jquery/footer.php
The old link is 404 and causes spider-check failures in the api.jquery.com repository, see e.g.:
https://github.com/jquery/api.jquery.com/actions/runs/14419108308/job/40439439869?pr=1275
> jquery: Update the link to Learning jQuery: Fourth Edition in the footer

- themes/jquery/css/base.css
As said by @sschmitz1414 in the api.jquery.com issue [Usability Error - Links](https://github.com/jquery/api.jquery.com/issues/1222).
> The "Also in" section in the list of Methods in the API Documentation as seen below can be a usability error. It is not clear that they are links due to being grey and not blue, they have no underline even when you hover on them, and it isn't clear where one link ends and another begins (for example Manipulate and Class Attribute are separate links even though the share the same "button" or border.
This PR aims to fix that by adding a blue color and the underline to the individual links, alongside increasing the visibility of the "Also in" section by darkening the text color a bit.
Resulting in the following look:
Related to/Fixes api.jquery.com issue …
> Updating "Also in" link styles for better usability

- themes/jquery/css/base.css
Relates to grunt-jquery-content issue [#95](https://github.com/jquery/grunt-jquery-content/pull/95)
> Adding top margin to example header
